### ISSUE TITLE
`no_builtin` attribute support

### ISSUE THREAD

**Issue by alexrp** [fuhsnn/slimcc#107]
See: https://clang.llvm.org/docs/AttributeReference.html#no-builtin

I'll likely make Zig's `zig.h` make use of this attribute soon, so it would be nice if slimcc could recognize it. Note that for Zig we only need the simple form (`__attribute__((no_builtin))`).

**Comment by alexrp** [comment]
Similarly, recognizing `-f(no-)builtin` would also be helpful.

**Comment by alexrp** [comment]
Clang's attribute does two distinct but related things:

1. It makes it so that e.g. a call to `memcpy()` in source code is not recognized as special and replaced with something else (such as `__aeabi_memcpy()`).
2. It makes it so that certain code sequences are not replaced with special library calls (such as a naïve copy loop being replaced with `memcpy()`).

(1) corresponds to LLVM's `nobuiltin` call site attribute. (2) corresponds to LLVM's `no-builtins` function attribute. (Very helpful name choices, right?)

**Comment by fuhsnn** [comment]
Thanks for the detail, and the kind heads-up! 

Yeah, no problem, I'll support it.
