### ISSUE TITLE
`localtime()` may set ENOENT in some docker environment

### ISSUE THREAD

**Issue by iphydf** [fuhsnn/slimcc#69]
https://github.com/fuhsnn/slimcc/commit/7b7c98604ab3eb85e68d7b3ae7f884d5537638c8 the assert added here triggers.

Input file:
```c
#include <assert.h>
```

Another option:
```c
#include ""
```

**Comment by fuhsnn** [comment]
I tracked this down. 
It looks like localtime() set errno if the compiled executable is executed with docker `RUN`, but not with `CMD`.
Minimal repro:

localtime_errno.c
```
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <errno.h>

int main(void) {
  time_t now = time(NULL);
  if (errno)
    fprintf(stderr, "time() set errno to %d", errno), exit(1);

  struct tm *tmp = localtime(&now);
  if (!tmp)
    fprintf(stderr, "localtime() return null"), exit(1);
  if (errno)
    fprintf(stderr, "localtime() set errno to %d", errno), exit(1);
}
```
dockerfile
```
...
WORKDIR /work/localtime_errno_test
COPY localtime_errno.c /work/localtime_errno_test/
RUN gcc localtime_errno.c -o out

CMD ./out #good
#RUN ./out #bad
```

**Comment by fuhsnn** [comment]
Tried a few more dockerhub images
`localtime()` set ENOENT: `alpine:latest`, `ubuntu:20.04`
`localtime()` doesn't set ENOENT `fedora:40` `debian:latest` `gcc:latest`

Anyway, I removed the assert and `main` should be good now.
